### ISSUE TITLE
msgpack encoding and decoding of erlang maps is asymmetrical on null values

### ISSUE THREAD

**Issue by raghavkarol** [msgpack/msgpack-erlang#42]
13> Msg = #{"a" => null}.
#{"a" => null}
15> Packed = msgpack:pack(Msg).
<<129,145,97,192>>
17> {ok, Unpacked} = msgpack:unpack(Packed, [{format, map}]).
{ok,#{"a" => nil}}
24> Unpacked = Msg.
** exception error: no match of right hand side value #{"a" => null}

**Comment by kuenishi** [comment]
OK. I understand the problem. Options for pack and unpack is recommended to be the same as much as you can; msgpack-erlang tries its best but sometimes it doesn't work. This time the confusion of `nil` and `null` value. When `{format, map}` is set, nil should be used. Default option for packing terms is `{format, jiffy}` for now, whose default is `null`. I think this will work for you, too:

```erlang
9> Msg = #{"a" => nil}.                        
#{"a" => nil}
10> Packed = msgpack:pack(Msg, [{format, map}]).
<<129,145,97,192>>
11> {ok, Unpacked} = msgpack:unpack(Packed, [{format, map}]).
{ok,#{"a" => nil}}
12> Unpacked = Msg.                                          
#{"a" => nil}
```

I will start thinking the best way to prevent confusion around null and nils in next release after #45 get merged. Thank you for reporting.

**Comment by kuenishi** [comment]
As of 0.4.0, `nil` is removed so this is supposed to be solved now.
