### ISSUE TITLE
Clean up various options and behaviours on maps, nil and null

### ISSUE THREAD

**Issue by kuenishi** [msgpack/msgpack-erlang#48]
Questions on next 0.4.0 work:

* Is (partial) compatibility with jsx and jiffy really needed ? MessagePack is close to JSON, somewhat compatible, but not JSON. Removing such compatibility will make the code a bit simpler than now.
* Support on 17.0 or older OTP versions, or not? Maybe just keep using 0.3.x is fine for them.
* `nil` is used in only jsx. How about deprecating it? [The spec](https://github.com/msgpack/msgpack/blob/master/spec.md#formats-nil) uses the term "nil", but can be replaced by "null" like JSON manner.

Other thoughts:

* maps are surely a default after 0.4.0 with 18.0.
* Is NIF version wanted? I heard some people like them because of speed and now the NIF interface has some functions on counting reductions to avoid messing up scheduler - might be good. But requiring C compiler to build msgpack-erlang might be an overhead for pure-Erlang people. Thoughts?
* Documentation. Interfaces could be stable after these fix up, and I often forget how this behaves.

**Comment by Licenser** [comment]
I think jiffy/jsx compatibility is a big plus. If msgpack is used on HTTP it seems like a natural pattern to offer it alongside a more common encoding (JSON) which can act as a fallback. Having compatibility with those two most common JSON libraries makes it possible to just drop in another de/en-coder and be done with it without needing to re-encode all the data for later processing.

**Comment by mururu** [comment]
> Is (partial) compatibility with jsx and jiffy really needed ? MessagePack is close to JSON, somewhat compatible, but not JSON. Removing such compatibility will make the code a bit simpler than now.
> Support on 17.0 or older OTP versions, or not? Maybe just keep using 0.3.x is fine for them.

`jsx` and `jiffy` supports maps now, so it is fair enough for me that 0.4.x supports only maps and works on 18.0 or later if 0.3.x is maintained.

> nil is used in only jsx. How about deprecating it? The spec uses the term "nil", but can be replaced by "null" like JSON manner.

Agreed.

> Is NIF version wanted?

I don't need NIF. If there are people want NIF version, how about create another repository for NIF?

**Comment by kuenishi** [comment]
[0.4.0 tagged](https://github.com/msgpack/msgpack-erlang/releases/tag/0.4.0). I think I have included all results of this discussion. Thank you for your contribution and usage.
