### ISSUE TITLE
Arrays with numbers and {enable_str, true}

### ISSUE THREAD

**Issue by comtihon** [msgpack/msgpack-erlang#51]
I use enable_str=true for new spec, as was adviced in https://github.com/msgpack/msgpack-erlang/issues/49
The problem is, when I have map with list, f.e. #{key => [56,57]} erlang treats it as "89". The problem is, that after encoding and decoding on client-side I got string "89".
Is there any opportunity to make msgpack encode this string as list?
Thanks.

**Comment by kuenishi** [comment]
That is a good question. Right now I indeed don't have good idea to solve that. As you already may know this stems from the fact that Erlang does not have native string type and using integer lists to represent strings.
Maybe an-unicode-binary-mode and never using binaries work? A quick workaround is just setting `{enable_str, false}` but that will not work for your Java code. Or wrapping such string like `{unicode, "Blahblàhblah"}` but this is not a standard way and may be inconvenient.

**Comment by comtihon** [comment]
may be library should take fun as a parameter to determine, wheter it is list or string for user to implement?

**Comment by kuenishi** [comment]
I opened a draft spec for this problem in #60, which will be a place for discussion.
