### ISSUE TITLE
Old rebar support broken?

### ISSUE THREAD

**Issue by stofel** [msgpack/msgpack-erlang#52]
./rebar get-deps
Uncaught error in rebar_core: {'EXIT',
                               {function_clause,
                                [{code,which,
                                  [{rebar3_eqc,".*",
                                    {git,
                                     "https://github.com/kellymclaughlin/rebar3-eqc-plugin.git",
                                     {tag,"0.0.8"}}}],
                                  [{file,"code.erl"},{line,412}]},
                                 {rebar_core,'-plugin_modules/3-lc$^0/1-0-',
                                  1,
                                  [{file,"src/rebar_core.erl"},{line,573}]},
                                 {rebar_core,plugin_modules,3,
                                  [{file,"src/rebar_core.erl"},{line,573}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,244}]},
                                 {rebar_core,process_each,5,
                                  [{file,"src/rebar_core.erl"},{line,351}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,253}]},
                                 {rebar_core,process_commands,2,
                                  [{file,"src/rebar_core.erl"},{line,93}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]}]}}
*** Error code 1

Stop.

**Comment by kuenishi** [comment]
It really looks like so... the workaround is to use `0.3.4` tag or `0.3` branch.

**Comment by okeuday** [comment]
There is nothing preventing you from supporting `rebar2` and `rebar3` with the same config, which would help you avoid breaking everyone that uses this repo as a dependency with `rebar2` projects.
