### ISSUE TITLE
hex.pm package

### ISSUE THREAD

**Issue by okeuday** [msgpack/msgpack-erlang#53]
I need a hex package for version `0.3.4` of this repo.  Currently, Erlang packages are suppose to use rebar3 for creating hex packages, though they can also be created by mix (from Elixir).  The Elixir library has already been added from https://github.com/mururu/msgpack-elixir to https://github.com/msgpack/msgpack-erlang .  If you use mix to add the package, it just requires `language: :erlang` in the project data provided in the `mix.exs` file.  I can add a pull request for this if you want.

**Comment by kuenishi** [comment]
Thank you for heads up. I'd recommend `0.4.0` if you're using OTP 17 or 18 because it has rebar3, maps and cleaner codes and interfaces. This is mainline. I'm not familiar with Elixir and its packaging system, so pull requests on this would be welcomed.

`0.3.4` along with `0.3` branch is for R16B or R15B, which is only left for old OTP versions. I don't like changing much on this branch like moving to rebar3. But if you still need this branch, please open a pull request against `0.3` branch.

**Comment by okeuday** [comment]
I published the `0.3.5` hex package with the configuration in the pull request.  The current `0.4.0` release is using rebar3, so it probably is safest to use rebar3 for publishing the hex package.  Unfortunately, the rebar.config file can't be used with both rebar2 and rebar3 with its current format.  Also, it is bad to checkin opaque binary executables into a source code repository (`rebar` and `rebar3`) due to no versioning of the rebar source code and no insight into what surprises they may contain.  So, it would be really nice if you removed the rebar3 executable and are able to submit a hex package with rebar3.  Thanks!

**Comment by okeuday** [comment]
The other problem with the repository is the usage of `git` for the version, which isn't standard for Erlang/OTP, making it more difficult to use the source code outside of this repository.  It would be simplest to satisfy all use with updating the version as a string when the repository is tagged.

**Comment by kuenishi** [comment]
@okeuday , Thank you for creating hex package at Hex.pm. Publishing a hex package via rebar3 seems extremely easy and I tried with 0.4.0. But it looks like you're current owner of msgpack in Hex.pm and I failed. Could you add me `kuenishi at gmail.com` as another owner to maintain mainline in Hex.pm?

**Comment by okeuday** [comment]
@kuenishi You are added now so it should be fine.  Sorry about that.

**Comment by kuenishi** [comment]
No problem, thank you for quick response and I published 0.4.0.
