### ISSUE TITLE
Current plugins don't belong in top level plugins

### ISSUE THREAD

**Issue by tsloughter** [msgpack/msgpack-erlang#63]
You should have `rebar3_hex` plugin in either your global `~/.config/rebar3/rebar.config` configuration `plugins` list or as a `project_plugins` in the config so it does not get added to plugins when msgpack-erlang is a dependency of another project.

The eqc plugin should go under the `test` profile or also be a `project_plugins` since it should not be fetched when `msgpack-erlang` is used as a dep of another project since it is only for tests.

**Comment by kuenishi** [comment]
Thank you for review. I think I've addressed your comment in #64.
