### ISSUE TITLE
valid msgpacked bytes gives incomplete with erlang msgpack.

### ISSUE THREAD

**Issue by ginahagg** [msgpack/msgpack-erlang#66]
this is my packed erlang msgpack binary that i receive from clojure msgpack packer:
<<131,164,110,97,109,101,170,67,111,110,102,105,103,82,101,115,112,166,110,111,100,101,105,100,145,167,78,48,103,105,110,97,51,167,107,118,112,97,105,114,115,222,0,54,174,115,101,110,115,111,114,46,112,99,46,112,105,110,116,206,0,54,238,128,174,115,101,110,115,111,114,46,114,102,46,112,105,110,116,206,0,54,238,128,175,110,101,116,119,111,114,107,89,80,97,115,115,107,101,121,169,107,101,110,116,115,112,101,101,100,173,115,101,110,115,111,114,46,84,46,112,105,110,116,206,0,9,39,192,173,115,101,110,115,111,114,46,118,46,100,105,110,116,205,117,48,166,115,101,114,118,101,114,172,49,48,46,50,48,46,49,48,56,46,57,50,172,110,101,116,119,111,114,107,88,83,83,73,68,174,83,101,110,115,105,116,121,68,101,102,97,117,108,116,174,115,101,110,115,111,114,46,97,105,46,109,111,100,101,1,173,115,101,110,115,111,114,46,116,46,109,111,100,101,1,175,115,101,110,115,111,114,46,97,80,70,46,100,105,110,116,205,117,48,173,115,101,110,115,111,114,46,112,46,109,111,100,101,2,175,115,101,110,115,111,114,46,108,73,82,46,112,105,110,116,206,0,54,238,128,174,115,101,110,115,111,114,46,97,119,46,100,105,110,116,205,117,48,175,115,101,110,115,111,114,46,109,80,70,46,112,105,110,116,206,0,54,238,128,174,115,101,110,115,111,114,46,112,99,46,100,105,110,116,205,117,48,174,115,101,110,115,111,114,46,109,119,46,109,111,100,101,1,174,115,101,110,115,111,114,46,109,116,46,100,105,110,116,205,117,48,173,115,101,110,115,111,114,46,108,46,109,111,100,101,1,175,115,101,110,115,111,114,46,109,80,70,46,100,105,110,116,205,117,48,174,115,101,110,115,111,114,46,109,119,46,100,105,110,116,205,117,48,174,115,101,110,115,111,114,46,97,105,46,112,105,110,116,206,0,54,238,128,176,110,101,116,119,111,114,107,88,83,101,99,117,114,105,116,121,165,119,112,97,50,112,174,115,101,110,115,111,114,46,109,105,46,109,111,100,101,1,175,115,101,110,115,111,114,46,97,80,70,46,112,105,110,116,206,0,54,238,128,175,115,101,110,115,111,114,46,97,80,70,46,109,111,100,101,1,174,115,101,110,115,111,114,46,109,116,46,109,111,100,101,1,175,115,101,110,115,111,114,46,109,80,70,46,109,111,100,101,1,175,115,101,110,115,111,114,46,108,73,82,46,100,105,110,116,205,117,48,176,110,101,116,119,111,114,107,89,83,101,99,117,114,105,116,121,165,119,112,97,50,112,174,115,101,110,115,111,114,46,109,105,46,112,105,110,116,206,0,54,238,128,174,115,101,110,115,111,114,46,114,102,46,100,105,110,116,205,117,48,174,115,101,110,115,111,114,46,109,105,46,100,105,110,116,205,117,48,175,115,101,110,115,111,114,46,108,73,82,46,109,111,100,101,1,173,115,101,110,115,111,114,46,112,46,100,105,110,116,205,117,48,173,115,101,110,115,111,114,46,108,46,112,105,110,116,206,0,54,238,128,174,115,101,110,115,111,114,46,97,119,46,112,105,110,116,206,0,9,39,192,168,99,111,110,102,105,103,105,100,217,36,53,50,102,55,52,98,57,48,45,102,48,55,48,45,49,49,101,53,45,97,98,101,49,45,99,49,50,52,102,57,48,48,98,52,50,48,174,115,101,110,115,111,114,46,97,105,46,100,105,110,116,205,117,48,173,115,101,110,115,111,114,46,112,46,112,105,110,116,205,3,232,173,115,101,110,115,111,114,46,84,46,109,111,100,101,1,173,115,101,110,115,111,114,46,116,46,100,105,110,116,205,117,48,173,115,101,110,115,111,114,46,118,46,109,111,100,101,1,173,115,101,110,115,111,114,46,118,46,112,105,110,116,206,0,54,238,128,172,110,101,116,119,111,114,107,89,83,83,73,68,166,88,101,114,97,76,52,174,115,101,110,115,111,114,46,114,102,46,109,111,100,101,1,175,110,101,116,119,111,114,107,88,80,97,115,115,107,101,121,169,107,101,110,116,115,112,101,101,100,173,115,101,110,115,111,114,46,84,46,100,105,110,116,205,117,48,173,115,101,110,115,111,114,46,116,46,112,105,110,116,206,0,54,238,128,174,115,101,110,115,111,114,46,97,119,46,109,111,100,101,1,174,115,101,110,115,111,114,46,112,99,46,109,111,100,101,1,174,115,101,110,115,111,114,46,109,119,46,112,105,110,116,206,0,9,39,192,173,115,101,110,115,111,114,46,108,46,100,105,110,116,205,117,48,171,99,111,110,102,105,103,84,111,107,101,110,168,55,99,57,56,99,53,52,101,174,115,101,110,115,111,114,46,109,116,46,112,105,110,116,206,0,54,238,128>>

This comes through zmq from a clojure msgpack packer. When i try above binary as byte array on 
http://kawanet.github.io/msgpack-lite/  , it gives me the original message. 
But, erlang msgpack:unpack(M, [{format,map}] or msgpack:unpack(M) all returns {error,incomplete}, or msgpack:unpack_stream etc. 
what is missing? It is valid in clojure and javascript msgpack.

**Comment by ginahagg** [comment]
seems to be having problem with this particularly. (this is from msgpack-lite demo site)
http://kawanet.github.io/msgpack-lite/
{
  "configid": "52f74b90-f070-11e5-abe1-c124f900b420"
}

the binary i get is from above.
N1= <<129, 168, 99, 111, 110, 102, 105, 103, 105, 100, 217, 36, 53, 50, 102, 55, 52, 98, 57, 48, 45, 102, 48, 55, 48, 45, 49, 49, 101, 53, 45, 97, 98, 101, 49, 45, 99, 49, 50, 52, 102, 57, 48, 48, 98, 52, 50, 48>>.

it is having hard time with this starting at 217,36
<<"Ù$52f74b90-f070-11e5-abe1-c124f900b420">>

msgpack:unpack(N1,[{format,map}]).                                                                                                                                           L:<<"configid">>, V:8, Rest:<<"Ù$52f74b90-f070-11e5-abe1-c124f900b420">>
{error,incomplete}

**Comment by ginahagg** [comment]
seems like erlang is using 218,, and kawanet is using 217.. i don't know if that makes a difference.
although kawanet translates erlang bytes correctly..
M = #{<<“configid”>> => <<“52f74b90-f070-11e5-abe1-c124f900b420”>>}.
K = msgpack:pack(M,[{format,map}]).
<<129,168,99,111,110,102,105,103,105,100,218,0,36,53,50,102,55,52,98,57,48,45,
  102,48,55,48,45,49,49,101,53,45,97,98,101,49,45,99,49,50,52,102,57,48,48,98,
  52,50,48>>

from kawanet site..
{
"configid": "52f74b90-f070-11e5-abe1-c124f900b420"
}
  [129, 168, 99, 111, 110, 102, 105, 103, 105, 100, 217, 36, 53, 50, 102, 55, 52, 98, 57, 48, 45, 102, 48, 55, 48, 45, 49, 49, 101, 53, 45, 97, 98, 101, 49, 45, 99, 49, 50, 52, 102, 57, 48, 48, 98, 52, 50, 48]

**Comment by ginahagg** [comment]
Closing issue because the serializer (Clojure) needs to implement a serializer that provides a compatibility switch that will force str16 serializations.

**Comment by kuenishi** [comment]
@ginahagg What version of msgpack-erlang are you using? I'm afraid you're using old version, which doesn't have enough tests. The latest 0.5.0 handles this well, as I did add more tests recently.

```erlang
13> msgpack:unpack( <<129, 168, 99, 111, 110, 102, 105, 103, 105, 100, 217, 36, 53, 50, 102, 55, 52, 98, 57, 48, 45, 102, 48, 55, 48, 45, 49, 49, 101, 53, 45, 97, 98, 101, 49, 45, 99, 49, 50, 52, 102, 57, 48, 48, 98, 52, 50, 48>>, [{unpack_str, as_binary}]).
{ok,#{<<"configid">> => <<"52f74b90-f070-11e5-abe1-c124f900b420">>}}
```

**Comment by ginahagg** [comment]
Was using 0.3.6, the latest release.. Thanks for answering. I will use 0.5 and test it again.
