### ISSUE TITLE
binary cost large memory

### ISSUE THREAD

**Issue by DehaiWang** [msgpack/msgpack-erlang#67]
The datas is like "[1, 2, 3, 4, [1, 2, 3, 4], [<<"1">>, <<"2">>,<<"">>>], [<<"一二">>, <<"二三">>,<<"三四">>, <<"四五">>]]",and is repeated 100*10000 times.
I get binarys by using python3.3 msgpack ,write binarys into txt file,
and  read Binarys from txt file using erlang.

the erlang code is :
`{ok, Binarys} = file:read_file(FileName),
{Time_Unpack,Value} = timer:tc(msgpack,unpack,[Binarys,[ {unpack_str, as_binary}]]),
    io:format("Time_Unpack:~w~n",[Time_Unpack]),`

and the werl.exe process will cost about 2G memory.

erlang:memory().
[{total,5356408192},
 {processes,5258409720},
 {processes_used,5258409496},
 {system,97998472},
 {atom,202481},
 {atom_used,186288},
 {binary,90059376},
 {code,4512629},
 {ets,256136}]

**Comment by kuenishi** [comment]
I'm afraid your code has something wrong.

```erlang
8> {ok, B} = file:read_file("/Users/kuenishi/file").                    
{ok,<<"[1, 2, 3, 4, [1, 2, 3, 4], [<<\"1\">>, <<\"2\">>,<<\"\">>>], [<<\""...>>} 
9> io:put_chars(B).                                                     
[1, 2, 3, 4, [1, 2, 3, 4], [<<"1">>, <<"2">>,<<"">>>], [<<"一二">>, <<"二三">>,<<"三四">>, <<"四五">>]]
ok
10> msgpack:unpack(B, [{unpack_str, as_binary}]).                        
{error,not_just_binary}
```

**Comment by DehaiWang** [comment]
sorry,maybe my description is not clear.
I wirte in file by python3,and read from file by erlang17.
The python code is as follow:
`    
    file_path = 'F:/binary/test.txt'
    datas = []
    model = [1, 2, 3, 4, [1, 2, 3, 4], ['1', '2', '3'], ['一二', '二三', '三四', '四五']]
    count = 100*10000
    index = 0
    while index < count:
        datas += model
        index += 1
            
    import msgpack
    packed_binary = msgpack.packb(datas
                                   , use_bin_type=True
                                    , encoding='utf-8'
                                   )

    # write binary into file
    file_object = open(file_path, 'wb')
    file_object.write(packed_binary)
    file_object.close( )`


and the erlang code is as follow:
`FileName ="F:/binary/test.txt",
{ok, Binarys} = file:read_file(FileName),
 Value =  msgpack:unpack( Binarys,[ {unpack_str, as_binary}]),
 {ok,Datas}=Value,
 Datas.`

After the erlang codes is complete,the memory that the werl.exe process  costs  increases more than 1.2G .
Then I do "erlang:garbage_collect()", the memory that the werl.exe process  costs   decrease about 0.6G .
But i donot understand where the left 0.6G memory cost .

If i repeate ,the momery increates 0.6G  every time.

**Comment by DehaiWang** [comment]
`-module (msgpack_test).
-compile(export_all).
test_unpack_1()->
	FileName ="F:/binary/test.txt",
	{ok, Binarys} = file:read_file(FileName),
	 Value =  msgpack:unpack( Binarys,[ {unpack_str, as_binary}]),
    {ok,_Datas}=Value,
    ok.
test_unpack_2()->
	FileName ="F:/binary/test.txt",
	{ok, Binarys} = file:read_file(FileName),
	 Value =  msgpack:unpack( Binarys,[ {unpack_str, as_binary}]),
    {ok,Datas}=Value,
    Datas.`



I am puzzled..........
If i do "msgpack_test:test_unpack_1()",the memory is unchanged.
If i do "msgpack_test:test_unpack_2()",the memory is growing.

**Comment by mururu** [comment]
Thanks. I can reproduce it.

**Comment by mururu** [comment]
@DehaiWang The Erlang shell keeps results from previous commands. The 0.6G is the size of the result of ` msgpack_test:test_unpack2/0`.
If you don't want to keep results, you can use `results/1`.
http://erlang.org/doc/man/shell.html

For exmaple,
```
1> results(0).
2> msgpack_test:test_unpack2().
3> erlang:garbage_collect().
```
the result of `msgpack_test:test_unpack2()` is garbage-collected.

Thanks!
