### ISSUE TITLE
Add 19.0 to .travis.yaml

### ISSUE THREAD

**Issue by kuenishi** [msgpack/msgpack-erlang#70]
After 19.0 release I hope somebody poll Travis-CI to implement 19.0 in its infrastructure. c.f. #69

**Comment by optikfluffel** [comment]
As far as I know Travis uses [kerl](https://github.com/kerl/kerl) for installing Erlang so if we're lucky it just works™️ when kerl supports it 😀

**Comment by okeuday** [comment]
You can add `18.3` and `19.0` to the travis config now (using them in other repos).  Could you make a new release that is added as a hex package?

**Comment by kuenishi** [comment]
Done. Thank you for notifying! https://hex.pm/packages/msgpack/0.6.0
