### ISSUE TITLE
Support unpack of Infinity and NaN values

### ISSUE THREAD

**Issue by alefend** [msgpack/msgpack-erlang#72]
If a msgpack-encoded binary contains the IEEE-754 values for Infinity and NaN, the `unpack` function returns the `{error, incomplete}` error.

This become an issue when the msgpack-encoded binary is generated from languages which can support every IEEE-754 value: if the decoding part is performed in Erlang, the whole msgpack content is discarded.

Here is an example of trying to deal with data generated from a foreign language:

```
1> MsgPackNaN = <<16#cb, 16#7f, 16#f8, 0, 0, 0, 0, 0, 0>>.
2> msgpack:unpack(MsgPackNaN).
{error, incomplete}

3> MsgPackPositiveInfinity = <<16#cb, 16#7f, 16#f0, 0, 0, 0, 0, 0, 0>>.
4> msgpack:unpack(MsgPackPositiveInfinity).
{error, incomplete}

5> MsgPackNegativeInfinity = <<16#cb, 16#ff, 16#f0, 0, 0, 0, 0, 0, 0>>.
6> msgpack:unpack(MsgPackNegativeInfinity).
{error, incomplete}
```

Can a special handling of this values be added to the library? Maybe by returning some ad-hoc atoms such as `nan` and `infinity` (or both `positive_infinity` and `negative_infinity`).

**Comment by mururu** [comment]
👍 > `nan`, `positive_infinity` and `negative_infinity`

@kuenishi What do you think?

**Comment by kuenishi** [comment]
@mururu @alefend wanna new version? I'd like this as 0.7.0 and a note on this behaviour added in README.md (not against merging it).

**Comment by mururu** [comment]
@kuenishi I agree to 0.7.0
