### ISSUE TITLE
Elixir/Erlang nil/null problem

### ISSUE THREAD

**Issue by grepz** [msgpack/msgpack-erlang#82]
Having some problems with elixir/erlang null/nil coding/decoding. 
Jiffy has wonderful option use_nil, which does following:
```
 jiffy:encode(#{a => nil}, [use_nil]).
<<"{\"a\":null}">>
```
Why not use same approach in msgpack? Having similar option that handles nil/null as one entity. Changes in code are minimal.

**Comment by grepz** [comment]
https://github.com/msgpack/msgpack-erlang/pull/83

**Comment by kuenishi** [comment]
Thanks @grepz , this issue has been fixed as of 0.8.1.
